# SPDX-FileCopyrightText: 2021 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.1.4.2015.1183.2");
  script_cve_id("CVE-2014-3570", "CVE-2014-3572", "CVE-2014-8275", "CVE-2015-0204", "CVE-2015-0205", "CVE-2015-0286", "CVE-2015-0287", "CVE-2015-0288", "CVE-2015-0289", "CVE-2015-0292", "CVE-2015-0293", "CVE-2015-1789", "CVE-2015-1790", "CVE-2015-4000");
  script_tag(name:"creation_date", value:"2021-06-09 14:58:12 +0000 (Wed, 09 Jun 2021)");
  script_version("2025-08-15T15:42:24+0000");
  script_tag(name:"last_modification", value:"2025-08-15 15:42:24 +0000 (Fri, 15 Aug 2025)");
  script_tag(name:"cvss_base", value:"7.5");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:P/A:P");
  script_tag(name:"severity_vector", value:"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H");
  script_tag(name:"severity_origin", value:"NVD");
  script_tag(name:"severity_date", value:"2015-06-15 15:14:35 +0000 (Mon, 15 Jun 2015)");

  script_name("SUSE: Security Advisory (SUSE-SU-2015:1183-2)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2021 Greenbone AG");
  script_family("SuSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/suse_sles", "ssh/login/rpms", re:"ssh/login/release=(SLES10\.0SP4)");

  script_xref(name:"Advisory-ID", value:"SUSE-SU-2015:1183-2");
  script_xref(name:"URL", value:"https://www.suse.com/support/update/announcement/2015/suse-su-20151183-2.html");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/912014");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/912015");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/912018");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/912293");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/912296");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/922488");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/922496");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/922499");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/922500");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/922501");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/929678");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/931698");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/934489");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/934491");
  script_xref(name:"URL", value:"https://lists.suse.com/pipermail/sle-security-updates/2015-July/001482.html");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'compat-openssl097g' package(s) announced via the SUSE-SU-2015:1183-2 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"OpenSSL was updated to fix several security issues:

 * CVE-2015-4000: The Logjam Attack ( weakdh.org ) has been addressed by
 rejecting connections with DH parameters shorter than 1024 bits.
 2048-bit DH parameters are now generated by default.
 * CVE-2015-1789: An out-of-bounds read in X509_cmp_time was fixed.
 * CVE-2015-1790: A PKCS7 decoder crash with missing EnvelopedContent
 was fixed.
 * Fixed a timing side channel in RSA decryption. (bsc#929678)

Additional changes:

 * In the default SSL cipher string EXPORT ciphers are now disabled.
 This will only get active if applications get rebuilt and actually
 use this string. (bsc#931698)

Security Issues:

 * CVE-2015-1789
 <[link moved to references]>
 * CVE-2015-1790
 <[link moved to references]>
 * CVE-2015-4000
 <[link moved to references]>");

  script_tag(name:"affected", value:"'compat-openssl097g' package(s) on SUSE Linux Enterprise Desktop 11-SP3, SUSE Linux Enterprise Server for SAP Applications 11-SP3.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "SLES10.0SP4") {

  if(!isnull(res = isrpmvuln(pkg:"compat-openssl097g", rpm:"compat-openssl097g~0.9.7g~13.31.1", rls:"SLES10.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"compat-openssl097g-32bit", rpm:"compat-openssl097g-32bit~0.9.7g~13.31.1", rls:"SLES10.0SP4"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
