# SPDX-FileCopyrightText: 2024 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.856737");
  script_cve_id("CVE-2024-28168");
  script_tag(name:"creation_date", value:"2024-11-27 05:00:20 +0000 (Wed, 27 Nov 2024)");
  script_version("2025-08-15T15:42:26+0000");
  script_tag(name:"last_modification", value:"2025-08-15 15:42:26 +0000 (Fri, 15 Aug 2025)");
  script_tag(name:"cvss_base", value:"5.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:N/A:N");

  script_name("openSUSE Security Advisory (SUSE-SU-2024:4054-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2024 Greenbone AG");
  script_family("openSUSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/opensuse", "ssh/login/rpms", re:"ssh/login/release=openSUSELeap15\.5|openSUSELeap15\.6");

  script_xref(name:"Advisory-ID", value:"SUSE-SU-2024:4054-1");
  script_xref(name:"URL", value:"https://www.suse.com/support/update/announcement/2024/suse-su-20244054-1.html");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1231347");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1231428");
  script_xref(name:"URL", value:"https://lists.suse.com/pipermail/sle-security-updates/2024-November/019844.html");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'javapackages-tools, xmlgraphics-batik, xmlgraphics-commons, xmlgraphics-fop' package(s) announced via the SUSE-SU-2024:4054-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for javapackages-tools, xmlgraphics-batik, xmlgraphics-commons, xmlgraphics-fop fixes the following issues:

xmlgraphics-fop was updated from version 2.8 to 2.10:

- Security issues fixed:

 * CVE-2024-28168: Fixed improper restriction of XML External Entity (XXE) reference (bsc#1231428)

- Upstream changes and bugs fixed:

 * Version 2.10:

 + footnote-body ignores rl-tb writing mode
 + SVG tspan content is displayed out of place
 + Added new schema to handle pdf/a and pdfa/ua
 + Correct fop version at runtime
 + NoSuchElementException when using font with no family name
 + Resolve classpath for binary distribution
 + Switch to spotbugs
 + Set an automatic module name
 + Rename packages to avoid conflicts with modules
 + Resize table only for multicolumn page
 + Missing jars in servlet
 + Optimise performance of PNG with alpha using raw loader
 + basic-link not navigating to corresponding footnote
 + Added option to sign PDF
 + Added secure processing for XSL input
 + Allow sections which need security permissions to be run when AllPermission denied in caller code
 + Remove unused PDFStructElem
 + Remove space generated by fo:wrapper
 + Reset content length for table changing ipd
 + Added alt text to PDF signature
 + Allow change of resource level for SVG in AFP
 + Exclude shape not in clipping path for AFP
 + Only support 1 column for redo of layout without page pos only
 + Switch to Jakarta servlet API
 + NPE when list item is split alongside an ipd change
 + Added mandatory MODCA triplet to AFP
 + Redo layout for multipage columns
 + Added image mask option for AFP
 + Skip written block ipds inside float
 + Allow curly braces for src url
 + Missing content for last page with change ipd
 + Added warning when different pdf languages are used
 + Only restart line manager when there is a linebreak for blocklayout

 * Version 2.9:

 + Values in PDF Number Trees must be indirect references
 + Do not delete files on syntax errors using command line
 + Surrogate pair edge-case causes Exception
 + Reset character spacing
 + SVG text containing certain glyphs isn't rendered
 + Remove duplicate classes from maven classpath
 + Allow use of page position only on redo of layout
 + Failure to render multi-block itemBody alongside float
 + Update to PDFBox 2.0.27
 + NPE if link destination is missing with accessibility
 + Make property cache thread safe
 + Font size was rounded to 0 for AFP TTF
 + Cannot process a SVG using mvn jars
 + Remove serializer jar
 + Allow creating a PDF 2.0 document
 + Text missing after page break inside table inline
 + IllegalArgumentException for list in a table
 + Table width may be too wide when layout width changes
 + NPE when using broken link and PDF 1.5
 + Allow XMP at PDF page level
 + Symbol font was not being mapped to unicode
 + Correct font differences table for Chrome
 + Link against Java 8 API
 + Added support for ... [Please see the references for more information on the vulnerabilities]");

  script_tag(name:"affected", value:"'javapackages-tools, xmlgraphics-batik, xmlgraphics-commons, xmlgraphics-fop' package(s) on openSUSE Leap 15.5, openSUSE Leap 15.6.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "openSUSELeap15.5") {

  if(!isnull(res = isrpmvuln(pkg:"javapackages-filesystem", rpm:"javapackages-filesystem~6.3.4~150200.3.15.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-gradle", rpm:"javapackages-gradle~6.3.4~150200.3.15.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-ivy", rpm:"javapackages-ivy~6.3.4~150200.3.15.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-local", rpm:"javapackages-local~6.3.4~150200.3.15.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-tools", rpm:"javapackages-tools~6.3.4~150200.3.15.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"python3-javapackages", rpm:"python3-javapackages~6.3.4~150200.3.15.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik", rpm:"xmlgraphics-batik~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-css", rpm:"xmlgraphics-batik-css~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-demo", rpm:"xmlgraphics-batik-demo~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-javadoc", rpm:"xmlgraphics-batik-javadoc~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-rasterizer", rpm:"xmlgraphics-batik-rasterizer~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-slideshow", rpm:"xmlgraphics-batik-slideshow~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-squiggle", rpm:"xmlgraphics-batik-squiggle~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-svgpp", rpm:"xmlgraphics-batik-svgpp~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-ttf2svg", rpm:"xmlgraphics-batik-ttf2svg~1.18~150200.4.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-commons", rpm:"xmlgraphics-commons~2.10~150200.3.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-commons-javadoc", rpm:"xmlgraphics-commons-javadoc~2.10~150200.3.10.2", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-fop", rpm:"xmlgraphics-fop~2.10~150200.13.10.1", rls:"openSUSELeap15.5"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

if(release == "openSUSELeap15.6") {

  if(!isnull(res = isrpmvuln(pkg:"javapackages-filesystem", rpm:"javapackages-filesystem~6.3.4~150200.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-gradle", rpm:"javapackages-gradle~6.3.4~150200.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-ivy", rpm:"javapackages-ivy~6.3.4~150200.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-local", rpm:"javapackages-local~6.3.4~150200.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"javapackages-tools", rpm:"javapackages-tools~6.3.4~150200.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"python3-javapackages", rpm:"python3-javapackages~6.3.4~150200.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik", rpm:"xmlgraphics-batik~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-css", rpm:"xmlgraphics-batik-css~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-demo", rpm:"xmlgraphics-batik-demo~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-javadoc", rpm:"xmlgraphics-batik-javadoc~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-rasterizer", rpm:"xmlgraphics-batik-rasterizer~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-slideshow", rpm:"xmlgraphics-batik-slideshow~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-squiggle", rpm:"xmlgraphics-batik-squiggle~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-svgpp", rpm:"xmlgraphics-batik-svgpp~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-batik-ttf2svg", rpm:"xmlgraphics-batik-ttf2svg~1.18~150200.4.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-commons", rpm:"xmlgraphics-commons~2.10~150200.3.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-commons-javadoc", rpm:"xmlgraphics-commons-javadoc~2.10~150200.3.10.2", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"xmlgraphics-fop", rpm:"xmlgraphics-fop~2.10~150200.13.10.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
