# SPDX-FileCopyrightText: 2025 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.1.9.2025.81021009879810139998");
  script_cve_id("CVE-2024-41311");
  script_tag(name:"creation_date", value:"2025-05-26 07:22:06 +0000 (Mon, 26 May 2025)");
  script_version("2025-05-27T05:40:44+0000");
  script_tag(name:"last_modification", value:"2025-05-27 05:40:44 +0000 (Tue, 27 May 2025)");
  script_tag(name:"cvss_base", value:"9.4");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:C/I:C/A:N");
  script_tag(name:"severity_vector", value:"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N");
  script_tag(name:"severity_origin", value:"NVD");
  script_tag(name:"severity_date", value:"2025-03-24 14:41:38 +0000 (Mon, 24 Mar 2025)");

  script_name("Fedora: Security Advisory (FEDORA-2025-8fdb7be3cb)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2025 Greenbone AG");
  script_family("Fedora Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/fedora", "ssh/login/rpms", re:"ssh/login/release=FC41");

  script_xref(name:"Advisory-ID", value:"FEDORA-2025-8fdb7be3cb");
  script_xref(name:"URL", value:"https://bodhi.fedoraproject.org/updates/FEDORA-2025-8fdb7be3cb");
  script_xref(name:"URL", value:"https://bugzilla.redhat.com/show_bug.cgi?id=2319289");
  script_xref(name:"URL", value:"https://bugzilla.redhat.com/show_bug.cgi?id=2332519");
  script_xref(name:"URL", value:"https://github.com/advisories/GHSA-mwf7-wfvq-vc32");
  script_xref(name:"URL", value:"https://github.com/strukturag/libheif/releases");
  script_xref(name:"URL", value:"https://github.com/user-attachments/files/16734152/HEIF-images.zip");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'libheif' package(s) announced via the FEDORA-2025-8fdb7be3cb advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"Latest upstream release. It adds support for tiles and fixes reading images generated by iOS 18+. See [link moved to references] for more details about the changes since 1.17.6.

**NOTE:** `heif-convert` tool was renamed to `heif-dec`.

How to test:
==========

Download and unzip sample images from [mastodon issue #31570]([link moved to references]). Try opening them with e.g. `loupe` or `gimp`. They fail to open with `libheif-1.17.6`, but should open successfully with `libheif-1.19.5`.

Fixes [CVE-2024-41311]([link moved to references]) .");

  script_tag(name:"affected", value:"'libheif' package(s) on Fedora 41.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "FC41") {

  if(!isnull(res = isrpmvuln(pkg:"heif-pixbuf-loader", rpm:"heif-pixbuf-loader~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"heif-pixbuf-loader-debuginfo", rpm:"heif-pixbuf-loader-debuginfo~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libheif", rpm:"libheif~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libheif-debuginfo", rpm:"libheif-debuginfo~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libheif-debugsource", rpm:"libheif-debugsource~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libheif-devel", rpm:"libheif-devel~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libheif-tools", rpm:"libheif-tools~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"libheif-tools-debuginfo", rpm:"libheif-tools-debuginfo~1.19.5~3.fc41", rls:"FC41"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
