# SPDX-FileCopyrightText: 2025 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.1.18.1.2024.0005.1");
  script_cve_id("CVE-2023-48795");
  script_tag(name:"creation_date", value:"2025-03-03 04:06:28 +0000 (Mon, 03 Mar 2025)");
  script_version("2025-03-04T05:38:25+0000");
  script_tag(name:"last_modification", value:"2025-03-04 05:38:25 +0000 (Tue, 04 Mar 2025)");
  script_tag(name:"cvss_base", value:"5.4");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:H/Au:N/C:N/I:C/A:N");
  script_tag(name:"severity_vector", value:"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N");
  script_tag(name:"severity_origin", value:"NVD");
  script_tag(name:"severity_date", value:"2023-12-28 18:26:44 +0000 (Thu, 28 Dec 2023)");

  script_name("openSUSE Security Advisory (openSUSE-SU-2024:0005-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2025 Greenbone AG");
  script_family("openSUSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/opensuse", "ssh/login/rpms", re:"ssh/login/release=openSUSELeap15\.4");

  script_xref(name:"Advisory-ID", value:"openSUSE-SU-2024:0005-1");
  script_xref(name:"URL", value:"https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/BVOEVD2B4CFVDJEJANZW6QGRI6FTWFJ3/");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1218128");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'putty' package(s) announced via the openSUSE-SU-2024:0005-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for putty fixes the following issues:

putty was updated to to release 0.80:

 * Fix CVE-2023-48795 [boo#1218128]

- Update to release 0.79

 * Terminal mouse tracking: support for mouse movements which are
 not drags, and support for horizontal scroll events (e.g.
 generated by trackpads).
 * Fixed: PuTTY could fail an assertion if a resize control
 sequence was sent by the server while the window was docked to
 one half of the screen in KDE.
 * Fixed: PuTTY could fail an assertion if you tried to change the
 font size while the window was maximised.

- Update to release 0.78

 * Support for OpenSSH certificates, for both user
 authentication keys and host keys.
 * New SSH proxy modes, for running a custom shell command or
 subsystem on the proxy server instead of forwarding a port
 through it.
 * New plugin system to allow a helper program to provide
 responses in keyboard-interactive authentication, intended to
 automate one-time password systems.
 * Support for NTRU Prime post-quantum key exchange,
 * Support for AES-GCM (in the OpenSSH style rather than
 RFC 5647).
 * Support for more forms of Diffie-Hellman key exchange: new
 larger integer groups (such as group16 and group18), and
 support for using those and ECDH with GSSAPI.
 * Bug fix: server-controlled window title setting now works
 again even if the character set is ISO 8859 (or a few other");

  script_tag(name:"affected", value:"'putty' package(s) on openSUSE Leap 15.4.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "openSUSELeap15.4") {

  if(!isnull(res = isrpmvuln(pkg:"putty", rpm:"putty~0.80~bp154.2.3.1", rls:"openSUSELeap15.4"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
