# SPDX-FileCopyrightText: 2025 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.1.18.2.2025.02282.1");
  script_cve_id("CVE-2021-41190");
  script_tag(name:"creation_date", value:"2025-07-15 04:18:54 +0000 (Tue, 15 Jul 2025)");
  script_version("2025-08-15T15:42:26+0000");
  script_tag(name:"last_modification", value:"2025-08-15 15:42:26 +0000 (Fri, 15 Aug 2025)");
  script_tag(name:"cvss_base", value:"4.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:S/C:N/I:P/A:N");
  script_tag(name:"severity_vector", value:"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:L/A:N");
  script_tag(name:"severity_origin", value:"NVD");
  script_tag(name:"severity_date", value:"2021-11-22 14:59:26 +0000 (Mon, 22 Nov 2021)");

  script_name("openSUSE Security Advisory (SUSE-SU-2025:02282-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2025 Greenbone AG");
  script_family("openSUSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/opensuse", "ssh/login/rpms", re:"ssh/login/release=openSUSELeap15\.6");

  script_xref(name:"Advisory-ID", value:"SUSE-SU-2025:02282-1");
  script_xref(name:"URL", value:"https://www.suse.com/support/update/announcement/2025/suse-su-202502282-1.html");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1243388");
  script_xref(name:"URL", value:"https://github.com/opencontainers/umoci/releases/tag/v0.5.0");
  script_xref(name:"URL", value:"https://lists.suse.com/pipermail/sle-updates/2025-July/040691.html");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'umoci' package(s) announced via the SUSE-SU-2025:02282-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for umoci fixes the following issues:

Update to umoci v0.5.0. Upstream changelog is available from

 <[link moved to references]> bsc#1243388

A security flaw was found in the OCI image-spec, where it is possible to cause a blob with one media-type to be interpreted as a different media-type.
As umoci is not a registry nor does it handle signatures, this vulnerability had no real impact on umoci but for safety we implemented the now-recommended media-type embedding and verification. CVE-2021-41190

Other changes in this release:

 * Several large reworks and API-related changes to the umoci's overlayfs
 support. This is only available to Go API users.
 * The runtime-spec config.json generated by umoci is updated to be more
 modern and work properly with modern runc versions.
 * The default gzip compression blocksize has been adjusted to match Docker.
 * zstd-compressed images are now fully supported. Users can explcitily
 request the compression algorithm for newly-generated layers with the
 --compress option.");

  script_tag(name:"affected", value:"'umoci' package(s) on openSUSE Leap 15.6.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "openSUSELeap15.6") {

  if(!isnull(res = isrpmvuln(pkg:"umoci", rpm:"umoci~0.5.0~150000.3.15.1", rls:"openSUSELeap15.6"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
