# SPDX-FileCopyrightText: 2025 Greenbone AG
# Some text descriptions might be excerpted from (a) referenced
# source(s), and are Copyright (C) by the respective right holder(s).
#
# SPDX-License-Identifier: GPL-2.0-only

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.1.4.2025.0058.1");
  script_cve_id("CVE-2024-50379", "CVE-2024-52317", "CVE-2024-54677", "CVE-2024-56337");
  script_tag(name:"creation_date", value:"2025-01-13 04:17:21 +0000 (Mon, 13 Jan 2025)");
  script_version("2025-08-15T15:42:26+0000");
  script_tag(name:"last_modification", value:"2025-08-15 15:42:26 +0000 (Fri, 15 Aug 2025)");
  script_tag(name:"cvss_base", value:"5.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:N/A:N");

  script_name("SUSE: Security Advisory (SUSE-SU-2025:0058-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2025 Greenbone AG");
  script_family("SuSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/suse_sles", "ssh/login/rpms", re:"ssh/login/release=(SLES15\.0SP3|SLES15\.0SP4|SLES15\.0SP5)");

  script_xref(name:"Advisory-ID", value:"SUSE-SU-2025:0058-1");
  script_xref(name:"URL", value:"https://www.suse.com/support/update/announcement/2025/suse-su-20250058-1.html");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1233435");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1234663");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1234664");
  script_xref(name:"URL", value:"https://bugzilla.suse.com/1236809");
  script_xref(name:"URL", value:"https://lists.suse.com/pipermail/sle-security-updates/2025-January/020086.html");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'tomcat' package(s) announced via the SUSE-SU-2025:0058-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for tomcat fixes the following issues:

Update to Tomcat 9.0.98

- Fixed CVEs:
 + CVE-2024-54677: DoS in examples web application (bsc#1234664)
 + CVE-2024-50379: RCE due to TOCTOU issue in JSP compilation (bsc#1234663)
 + CVE-2024-52317: Request/response mix-up with HTTP/2 (bsc#1233435)
- Catalina
 + Add: Add option to serve resources from subpath only with WebDAV Servlet
 like with DefaultServlet. (michaelo)
 + Fix: Add special handling for the protocols attribute of SSLHostConfig in
 storeconfig. (remm)
 + Fix: 69442: Fix case sensitive check on content-type when parsing request
 parameters. (remm)
 + Code: Refactor duplicate code for extracting media type and subtype from
 content-type into a single method. (markt)
 + Fix: Compatibility of generated embedded code with components where
 constructors or property related methods throw a checked exception. (remm)
 + Fix: The previous fix for inconsistent resource metadata during concurrent
 reads and writes was incomplete. (markt)
 + Fix: 69444: Ensure that the javax.servlet.error.message request attribute
 is set when an application defined error page is called. (markt)
 + Fix: Avoid quotes for numeric values in the JSON generated by the status
 servlet. (remm)
 + Add: Add strong ETag support for the WebDAV and default servlet, which can
 be enabled by using the useStrongETags init parameter with a value set to
 true. The ETag generated will be a SHA-1 checksum of the resource content.
 (remm)
 + Fix: Use client locale for directory listings. (remm)
 + Fix: 69439: Improve the handling of multiple Cache-Control headers in the
 ExpiresFilter. Based on pull request #777 by Chenjp. (markt)
 + Fix: 69447: Update the support for caching classes the web application
 class loader cannot find to take account of classes loaded from external
 repositories. Prior to this fix, these classes could be incorrectly marked
 as not found. (markt)
 + Fix: 69466: Rework handling of HEAD requests. Headers explicitly set by
 users will not be removed and any header present in a HEAD request will
 also be present in the equivalent GET request. There may be some headers,
 as per RFC 9110, section 9.3.2, that are present in a GET request that are
 not present in the equivalent HEAD request. (markt)
 + Fix: 69471: Log instances of CloseNowException caught by
 ApplicationDispatcher.invoke() at debug level rather than error level as
 they are very likely to have been caused by a client disconnection or
 similar I/O issue. (markt)
 + Add: Add a test case for the fix for 69442. Also refactor references to
 application/x-www-form-urlencoded. Based on pull request #779 by Chenjp.
 (markt)
 + Fix: 69476: Catch possible ISE when trying to report PUT failure in the
 DefaultServlet. (remm)
 + Add: Add support for RateLimit header fields for HTTP (draft) in the
 RateLimitFilter. Based on pull request #775 provided by Chenjp. (markt)
 + Add: ... [Please see the references for more information on the vulnerabilities]");

  script_tag(name:"affected", value:"'tomcat' package(s) on SUSE Linux Enterprise Server 15-SP3, SUSE Linux Enterprise Server 15-SP4, SUSE Linux Enterprise Server 15-SP5, SUSE Linux Enterprise Server for SAP Applications 15-SP3, SUSE Linux Enterprise Server for SAP Applications 15-SP4, SUSE Linux Enterprise Server for SAP Applications 15-SP5.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "SLES15.0SP3") {

  if(!isnull(res = isrpmvuln(pkg:"tomcat", rpm:"tomcat~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-admin-webapps", rpm:"tomcat-admin-webapps~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-el-3_0-api", rpm:"tomcat-el-3_0-api~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-jsp-2_3-api", rpm:"tomcat-jsp-2_3-api~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-lib", rpm:"tomcat-lib~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-servlet-4_0-api", rpm:"tomcat-servlet-4_0-api~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-webapps", rpm:"tomcat-webapps~9.0.98~150200.74.1", rls:"SLES15.0SP3"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

if(release == "SLES15.0SP4") {

  if(!isnull(res = isrpmvuln(pkg:"tomcat", rpm:"tomcat~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-admin-webapps", rpm:"tomcat-admin-webapps~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-el-3_0-api", rpm:"tomcat-el-3_0-api~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-jsp-2_3-api", rpm:"tomcat-jsp-2_3-api~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-lib", rpm:"tomcat-lib~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-servlet-4_0-api", rpm:"tomcat-servlet-4_0-api~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-webapps", rpm:"tomcat-webapps~9.0.98~150200.74.1", rls:"SLES15.0SP4"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

if(release == "SLES15.0SP5") {

  if(!isnull(res = isrpmvuln(pkg:"tomcat", rpm:"tomcat~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-admin-webapps", rpm:"tomcat-admin-webapps~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-el-3_0-api", rpm:"tomcat-el-3_0-api~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-jsp-2_3-api", rpm:"tomcat-jsp-2_3-api~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-lib", rpm:"tomcat-lib~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-servlet-4_0-api", rpm:"tomcat-servlet-4_0-api~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"tomcat-webapps", rpm:"tomcat-webapps~9.0.98~150200.74.1", rls:"SLES15.0SP5"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
