name: OpenVAS Feed Split Sync

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch:

jobs:
  sync-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync git-lfs
          git lfs install

      - name: Prepare workspace
        run: mkdir -p feeds

      # === NVT FEED ===
      - name: Sync NVT Feed to temporary location
        run: |
          mkdir -p /tmp/openvas-nvt
          rsync -av --delete rsync://feed.community.greenbone.net:/nvt-feed/ /tmp/openvas-nvt/
          sync

      - name: Tar and split NVT Feed safely
        run: |
          tar -cf feeds/nvt-feed.tar -C /tmp openvas-nvt
          split -b 500m feeds/nvt-feed.tar feeds/nvt-part-
          i=1
          for part in feeds/nvt-part-*; do
            mkdir -p feeds/nvt-part-$i
            cat $part | tar -xf - -C feeds/nvt-part-$i
            cd feeds/nvt-part-$i
            git init
            git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-nvt-feed-part-$i.git
            git checkout -B main
            git lfs track "*.nasl"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update NVT feed part $i" || echo "No changes"
            git push origin main --force
            cd ../..
            i=$((i+1))
          done

      # === SCAP FEED ===
      - name: Sync SCAP Feed to temporary location
        run: |
          mkdir -p /tmp/openvas-scap
          rsync -av --delete rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/scap-data/ /tmp/openvas-scap/
          sync

      - name: Tar and split SCAP Feed safely
        run: |
          tar -cf feeds/scap-feed.tar -C /tmp openvas-scap
          split -b 500m feeds/scap-feed.tar feeds/scap-part-
          i=1
          for part in feeds/scap-part-*; do
            mkdir -p feeds/scap-part-$i
            cat $part | tar -xf - -C feeds/scap-part-$i
            cd feeds/scap-part-$i
            git init
            git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-scap-feed-part-$i.git
            git checkout -B main
            git lfs track "*.json.gz" "*.json" "*.xml"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update SCAP feed part $i" || echo "No changes"
            git push origin main --force
            cd ../..
            i=$((i+1))
          done

      # === CERT FEED ===
      - name: Sync CERT Feed to temporary location
        run: |
          mkdir -p /tmp/openvas-cert
          rsync -av --delete rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/cert-data/ /tmp/openvas-cert/
          sync

      - name: Push CERT Feed
        run: |
          tar -cf feeds/cert-feed.tar -C /tmp openvas-cert
          mkdir -p feeds/cert-temp
          cat feeds/cert-feed.tar | tar -xf - -C feeds/cert-temp
          cd feeds/cert-temp
          git init
          git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-cert-feed.git
          git checkout -B main
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update CERT feed" || echo "No changes"
          git push origin main --force
          cd ../..

      # === VT FEED ===
      - name: Sync VT Feed to temporary location
        run: |
          mkdir -p /tmp/openvas-vt
          rsync -av --delete rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/vt-data/ /tmp/openvas-vt/
          sync

      - name: Tar and split VT Feed safely
        run: |
          tar -cf feeds/vt-feed.tar -C /tmp openvas-vt
          split -b 500m feeds/vt-feed.tar feeds/vt-part-
          i=1
          for part in feeds/vt-part-*; do
            mkdir -p feeds/vt-part-$i
            cat $part | tar -xf - -C feeds/vt-part-$i
            cd feeds/vt-part-$i
            git init
            git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-vt-feed-part-$i.git
            git checkout -B main
            git lfs track "*.json.gz" "*.json"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update VT feed part $i" || echo "No changes"
            git push origin main --force
            cd ../..
            i=$((i+1))
          done
