name: OpenVAS Feed Split Sync

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch:

jobs:
  sync-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync and git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync git-lfs
          git lfs install

      - name: Prepare workspace
        run: |
          mkdir -p feeds/nvt feeds/scap feeds/cert feeds/vt

      # === NVT FEED ===
      - name: Sync NVT Feed
        run: rsync -av --delete rsync://feed.community.greenbone.net:/nvt-feed/ feeds/nvt/

      - name: Push NVT Feed (split in parts if >500MB)
        run: |
          cd feeds/nvt
          split -b 500m -d -a 1 --additional-suffix="" <(tar -cf - .) nvt-part-
          i=1
          for part in nvt-part-*; do
            mkdir -p ../nvt-part-$i
            tar -xf $part -C ../nvt-part-$i
            cd ../nvt-part-$i
            git init
            git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-nvt-feed-part-$i.git
            git checkout -B main
            git lfs track "*.nasl"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update NVT feed part $i" || echo "No changes"
            git push origin main --force
            cd ..
            i=$((i+1))
          done

      # === SCAP FEED ===
      - name: Sync SCAP Feed
        run: rsync -av --delete rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/scap-data/ feeds/scap/

      - name: Push SCAP Feed (split into parts)
        run: |
          cd feeds/scap
          split -b 500m -d -a 1 --additional-suffix="" <(tar -cf - .) scap-part-
          i=1
          for part in scap-part-*; do
            mkdir -p ../scap-part-$i
            tar -xf $part -C ../scap-part-$i
            cd ../scap-part-$i
            git init
            git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-scap-feed-part-$i.git
            git checkout -B main
            git lfs track "*.json.gz" "*.json" "*.xml"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update SCAP feed part $i" || echo "No changes"
            git push origin main --force
            cd ..
            i=$((i+1))
          done

      # === CERT FEED ===
      - name: Sync CERT Feed
        run: rsync -av --delete rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/cert-data/ feeds/cert/

      - name: Push CERT Feed
        run: |
          cd feeds/cert
          git init
          git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-cert-feed.git
          git checkout -B main
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update CERT feed" || echo "No changes"
          git push origin main --force

      # === VT FEED ===
      - name: Sync VT Feed
        run: rsync -av --delete rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/vt-data/ feeds/vt/

      - name: Push VT Feed (split into parts)
        run: |
          cd feeds/vt
          split -b 500m -d -a 1 --additional-suffix="" <(tar -cf - .) vt-part-
          i=1
          for part in vt-part-*; do
            mkdir -p ../vt-part-$i
            tar -xf $part -C ../vt-part-$i
            cd ../vt-part-$i
            git init
            git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-vt-feed-part-$i.git
            git checkout -B main
            git lfs track "*.json.gz" "*.json"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update VT feed part $i" || echo "No changes"
            git push origin main --force
            cd ..
            i=$((i+1))
          done
