name: OpenVAS Feed Sync

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true  # enable Git LFS

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync git-lfs
          git lfs install

      - name: Ensure feed directory structure
        run: |
          mkdir -p openvas-feeds/nvt-feed
          mkdir -p openvas-feeds/scap-feed
          mkdir -p openvas-feeds/cert-feed
          mkdir -p openvas-feeds/vt-feed

          # Add .gitkeep to track empty directories
          touch openvas-feeds/nvt-feed/.gitkeep
          touch openvas-feeds/scap-feed/.gitkeep
          touch openvas-feeds/cert-feed/.gitkeep
          touch openvas-feeds/vt-feed/.gitkeep

      - name: Pull NVT feed
        run: |
          rsync -avz --ignore-existing --progress rsync://feed.community.greenbone.net:/nvt-feed/ openvas-feeds/nvt-feed/

      - name: Pull SCAP feed
        run: |
          rsync -avz --ignore-existing --progress rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/scap-data/ openvas-feeds/scap-feed/

      - name: Pull CERT feed
        run: |
          rsync -avz --ignore-existing --progress rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/cert-data/ openvas-feeds/cert-feed/

      - name: Pull VT feed (Notus)
        run: |
          # Recursive sync of VT feed, including all subfolders
          rsync -avz --ignore-existing --progress rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/vt-data/ openvas-feeds/vt-feed/

      - name: Track large files with Git LFS
        run: |
          # Track all .gz files recursively in all feeds
          git lfs track "openvas-feeds/nvt-feed/**/*.gz"
          git lfs track "openvas-feeds/scap-feed/**/*.gz"
          git lfs track "openvas-feeds/cert-feed/**/*.gz"
          git lfs track "openvas-feeds/vt-feed/**/*.gz"
          git add .gitattributes

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add openvas-feeds/*
          git add -u

          # Only commit if changes exist
          git diff --cached --quiet || git commit -m "Incremental OpenVAS feed update [skip ci]"

          git push
