name: OpenVAS Feed Split Sync

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  sync-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync git-lfs
          git lfs install

      # -------------------------------
      # NVT Feed
      # -------------------------------
      - name: Sync NVT feed
        run: |
          mkdir -p /tmp/openvas-nvt
          rsync -av --delete --partial --inplace --update \
            rsync://feed.community.greenbone.net:/nvt-feed/ /tmp/openvas-nvt/

      - name: Split and Push NVT feed
        run: |
          i=1
          for folder in /tmp/openvas-nvt/*; do
            name=$(basename "$folder")
            repo="https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-nvt-feed-part-$i.git"

            mkdir -p feeds/nvt-part-$i
            rsync -a --delete "$folder/" feeds/nvt-part-$i/

            cd feeds/nvt-part-$i
            git init
            git remote add origin "$repo"
            git checkout -B main
            git lfs track "*.nasl" "*.json" "*.json.gz"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update NVT feed part $i" || echo "No changes"
            git pull --rebase origin main || true
            git push origin main --force
            cd ../..
            i=$((i+1))
          done

      # -------------------------------
      # SCAP Feed
      # -------------------------------
      - name: Sync SCAP feed
        run: |
          mkdir -p /tmp/openvas-scap
          rsync -av --delete --partial --inplace --update \
            rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/scap-data/ /tmp/openvas-scap/

      - name: Split and Push SCAP feed
        run: |
          i=1
          for folder in /tmp/openvas-scap/*; do
            repo="https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-scap-feed-part-$i.git"

            mkdir -p feeds/scap-part-$i
            rsync -a --delete "$folder/" feeds/scap-part-$i/

            cd feeds/scap-part-$i
            git init
            git remote add origin "$repo"
            git checkout -B main
            git lfs track "*.json" "*.json.gz" "*.xml" "*.xml.gz"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update SCAP feed part $i" || echo "No changes"
            git pull --rebase origin main || true
            git push origin main --force
            cd ../..
            i=$((i+1))
          done

      # -------------------------------
      # CERT Feed
      # -------------------------------
      - name: Sync CERT feed
        run: |
          mkdir -p /tmp/openvas-cert
          rsync -av --delete --partial --inplace --update \
            rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/cert-data/ /tmp/openvas-cert/

      - name: Split and Push CERT feed
        run: |
          i=1
          for folder in /tmp/openvas-cert/*; do
            repo="https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-cert-feed-part-$i.git"

            mkdir -p feeds/cert-part-$i
            rsync -a --delete "$folder/" feeds/cert-part-$i/

            cd feeds/cert-part-$i
            git init
            git remote add origin "$repo"
            git checkout -B main
            git lfs track "*.json" "*.json.gz" "*.xml" "*.xml.gz"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update CERT feed part $i" || echo "No changes"
            git pull --rebase origin main || true
            git push origin main --force
            cd ../..
            i=$((i+1))
          done

      # -------------------------------
      # VT Feed
      # -------------------------------
      - name: Sync VT feed
        run: |
          mkdir -p /tmp/openvas-vt
          rsync -av --delete --partial --inplace --update \
            rsync://feed.community.greenbone.net/community/vulnerability-feed/24.10/vt-data/ /tmp/openvas-vt/

      - name: Split and Push VT feed
        run: |
          i=1
          for folder in /tmp/openvas-vt/*; do
            repo="https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jbeasl7/openvas-vt-feed-part-$i.git"

            mkdir -p feeds/vt-part-$i
            rsync -a --delete "$folder/" feeds/vt-part-$i/

            cd feeds/vt-part-$i
            git init
            git remote add origin "$repo"
            git checkout -B main
            git lfs track "*.json" "*.json.gz" "*.nasl"
            git add .gitattributes
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update VT feed part $i" || echo "No changes"
            git pull --rebase origin main || true
            git push origin main --force
            cd ../..
            i=$((i+1))
          done
